spring.application.name=gateway
server.port=8080
#EUREKA_Registery
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Log routes
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Route /api/auth and /api/users to the user microservice (Eureka service id: user)
spring.cloud.gateway.routes[0].id=user-auth
spring.cloud.gateway.routes[0].uri=lb://user
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-users
spring.cloud.gateway.routes[1].uri=lb://user
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
